### ISSUE TITLE
multi-block implementation for more complex geometries

### ISSUE THREAD

**Issue by p-costa** [p-costa/CaNS#1]
Implementing a multi-block approach to handle more complex geometries (e.g. a T-Junction) while still using the FFT-based solver. This could be achieved by using a block cyclic reduction method to solve the resulting tri-diagonal system. Collaborators for helping out with this feature are very welcome!

**Comment by manmeet3591** [comment]
Hi 

I have developed my own 2D DNS parallel code, It would be great to collaborate on development to support complex geometries.

**Comment by p-costa** [comment]
Hi, thanks for your interest! Let's keep in touch by email.
