### ISSUE TITLE
Errors compiling for Cray machines

### ISSUE THREAD

**Issue by lcebaman** [p-costa/CaNS#3]
ftn -cpp -O2     -DDEBUG -DTIMING -c  chkdt.f90

module mod_chkdt
       ^
ftn-855 crayftn: ERROR MOD_CHKDT, File = chkdt.f90, Line = 1, Column = 8
  The compiler has detected errors in module "MOD_CHKDT".  No module information file will be created for this module.

**Comment by lcebaman** [comment]
They  seems to be coming from preprocessor clauses. Adding -F to compilation process would help. May send you a Makefile option for Crays, if of interest.

**Comment by p-costa** [comment]
Thanks for the feedback! I have access to a Cray machine and will test it myself. At this stage of the project I expect the users to simply adapt the makefile to the particular machine.
