### ISSUE TITLE
Error while running

### ISSUE THREAD

**Issue by manmeet3591** [p-costa/CaNS#4]
Hi 

I have successfully compiled CaNS on Aaditya HPC at IITM Pune. I am getting the following error while running the code.
$ mpirun -n 4 ./cans 
At line 100 of file main.f90 (unit = 99, file = '')
Fortran runtime error: File 'data/grid.bin' does not exist

Do we need the grid.bin file to run the program ?

**Comment by p-costa** [comment]
Hi,

No, that is an output file with the grid in z. You need to create a folder 'data' where you run your executable.
