### ISSUE TITLE
FFTW3 fortran

### ISSUE THREAD

**Issue by nyue** [p-costa/CaNS#6]
Hi,

  Is there a specific version of FFTW3 I should use ?

  I obtained the latest but when I build it, it seems the fortran bindings are missing when I link it to CaNS

Cheers

**Comment by p-costa** [comment]
Hi,

The latest version should work, if the libraries are installed where expected. How did you install it and in which OS?

**Comment by nyue** [comment]
My bad. I was trying to link/use the FFTW3 I build myself.

I switch to using the FFTW3 and Lapack shipped with CentOS 7 and it links with no issue.

Cheers
